runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 2
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
env_variables:
  SLACK_SIGNING_SECRET: "$SLACK_SIGNING_SECRET"
  SLACK_CLIENT_ID: "$SLACK_CLIENT_ID"
  SLACK_CLIENT_SECRET: "$SLACK_CLIENT_SECRET"
  SLACK_STATE_SECRET: "$SLACK_STATE_SECRET"
  ENCRYPTION_KEY: "$ENCRYPTION_KEY"
  BUFFER_KEY: "$BUFFER_KEY"
