name: Deploy to Google App Engine

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace credentials in app.yaml
        run: |
          sed -i -e 's/$SLACK_SIGNING_SECRET/${{ secrets.SLACK_SIGNING_SECRET }}/g' app.yaml
          sed -i -e 's/$SLACK_OAUTH_ENABLED/${{ secrets.SLACK_OAUTH_ENABLED }}/g' app.yaml
          sed -i -e 's/$SLACK_CLIENT_ID/${{ secrets.SLACK_CLIENT_ID }}/g' app.yaml
          sed -i -e 's/$SLACK_CLIENT_SECRET/${{ secrets.SLACK_CLIENT_SECRET }}/g' app.yaml
          sed -i -e 's/$SLACK_STATE_SECRET/${{ secrets.SLACK_STATE_SECRET }}/g' app.yaml
          sed -i -e 's/$ENCRYPTION_KEY/${{ secrets.ENCRYPTION_KEY }}/g' app.yaml
          sed -i -e 's/$BUFFER_KEY/${{ secrets.BUFFER_KEY }}/g' app.yaml

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show App Engine application URL
        run: echo ${{ steps.deploy.outputs.url }}
